spring.application.name=jobboard-backend

#============================
# Database Configuration
#============================
spring.datasource.url=jdbc:mysql://localhost:3306/jobboard_backend

spring.datasource.username=Amax
spring.datasource.password=Amarxxxx

#============================
# JPA/Hibernate Configuration
#============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#============================
# Server Configuration
#============================
server.port=808x

#===========================
gemini.api.model=gemini-2.0-flash
gemini.api.key=AxxxxxxxxxxxJIjE0Sk0suys-kSsciR6LdC2FSTcP1rmFrELPyM9T3zg